### PR TITLE
Allow directly copying the db.php file

### PR DESCRIPTION
**Pull request by aristath**
See details in #29

### CODE REVIEW

**Comment by aristath** [comment]
Hmmm actually this won't work... `WP_PLUGIN_DIR` is not defined when `db.php` gets loaded in Core 🤔

**Comment by adamziel** [comment]
@aristath yes, I just ran into that the other day. Perhaps we could use `__DIR__` instead?

**Comment by aristath** [comment]
@adamziel I just pushed an update if you ant to try this 👍

**Review by adamziel — APPROVED** [review]
This is awesome and worked for me, thank you @aristath !

**Pull request merged**
